### ISSUE TITLE
bug: For debian/ubuntu ,Reboot after the first installation

### ISSUE THREAD

**Issue by kevincaradant** [kevincaradant/VPN_LINUX_ODROID_RPI#17]
For only Ubuntu / Debian,

If we want to use the vpn, we haven't internet, problem about iptables but i don't know, how can i restart the service iptables which does not exist under this distribution.

So we have to restart the device just one time and after all work.

Under the other distribution, this problem does not appear because we have a service for iptables

**Comment by xrexzerox** [comment]
now its work fine for me thanks

**Comment by kevincaradant** [comment]
OK  great, thanks for the feedback
 :)
