### ISSUE TITLE
feat: Suggest different methods to encrypt data

### ISSUE THREAD

**Issue by kevincaradant** [kevincaradant/VPN_LINUX_ODROID_RPI#20]
By default we have The authentification and cipher in 256 bits.

We can suggest a minimal authentification , less powerfull but also less secure

**Comment by xrexzerox** [comment]
thanks i like your works

**Comment by kevincaradant** [comment]
Haha, I'm happy to hear that. 

Indeed, some issues are still opened, by missing of time. 

If you want, you can create a PR if you want to share your contribution.

**Comment by xrexzerox** [comment]
Hello Do You know about sofether too?
im interested on that on how to manage via php on the external host not vps

**Comment by kevincaradant** [comment]
Hi

Sorry never saw your message.

More than 5 years later,I hope you got your answer.

And the answer (on my side)  is 'no'. I don't know 'sofether' but I hope since the time, that you have found what you was looking for.

I closed this issue because I don't have time to suggest this feature
